const $=id=>document.getElementById(id), ns='http://www.w3.org/2000/svg';
const worker=new Worker('./worker.js',{type:'module'}), pending=new Map();
let request=0,epoch=0,view,page=0,tool='pan',busy=false,gesture=null,dirty=false,ready=false;
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function call(op,args={}){return new Promise((resolve,reject)=>{const id=++request;pending.set(id,{resolve,reject});worker.postMessage({id,op,page,...args},args.bytes?[args.bytes]:[]);});}
worker.onmessage=({data})=>{if(data.ready){ready=true;$('open').disabled=false;$('examples').disabled=false;status('Listo. Abre una nota o arrástrala aquí.');return;}if(data.fatal){status(data.fatal,true);return;}const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);};
worker.onerror=e=>{for(const p of pending.values())p.reject(Error(e.message));pending.clear();ready=false;status('Error del núcleo web: '+e.message,true);};
function resize(){if(!view)return;const fit=$('zoom').value==='fit';$('paper').style.width=(fit?Math.min(view.size[0],Math.max(100,$('viewport').clientWidth-40)):view.size[0]*Number($('zoom').value))+'px';}
function display(result){view=result;page=result.page;$('title').textContent=result.title||'Nota sin título';$('counts').textContent=`${result.visible_imported} elementos importados · ${result.visible_added} trazos nuevos · ${result.erased} borrados`;$('render').innerHTML=result.svg;$('overlay').setAttribute('viewBox',`0 0 ${result.size.join(' ')}`);$('overlay').replaceChildren();$('pageLabel').textContent=`Página ${page+1} de ${result.pages}`;$('undo').disabled=!result.can_undo;$('redo').disabled=!result.can_redo;$('prev').disabled=page===0;$('next').disabled=page+1===result.pages;$('warnings').textContent=result.warnings.join(' ');$('empty').hidden=true;$('editor').hidden=false;resize();}
function cancelGesture(){const old=gesture;gesture=null;if(old && $('paper').hasPointerCapture(old.id))$('paper').releasePointerCapture(old.id);$('overlay').replaceChildren();}
function canReplace(){return !dirty||confirm('Hay cambios sin guardar. ¿Abrir otro documento y descartarlos?');}
async function load(file,token=++epoch){if(!ready || token!==epoch)return;cancelGesture();busy=true;view=null;dirty=false;$('editor').hidden=true;$('empty').hidden=false;status('Abriendo documento…');try{const project=file.name?.toLowerCase().endsWith('.nfedit');if(file.size>(project?128:64)*1024*1024)throw Error('Archivo demasiado grande.');const bytes=await file.arrayBuffer();if(token!==epoch)return;const result=await call('open',{bytes,project,page:0});if(token!==epoch)return;display(result);status('Nota abierta. Elige Lápiz o Borrador para editar.');}catch(e){if(token===epoch)status('No se pudo abrir: '+e.message,true);}finally{if(token===epoch)busy=false;}}
async function action(op,args={}){if(!view||busy)return;if(!['draw','erase'].includes(op))cancelGesture();busy=true;const token=epoch;try{const result=await call(op,args);if(token!==epoch)return;const changed=view.edit_count!==result.edit_count;display(result);if(changed)dirty=true;status(op==='erase'?'Borrado aplicado. Puedes deshacerlo.':op==='view'?'Página abierta.':'Cambio aplicado.');}catch(e){if(token===epoch){$('overlay').replaceChildren();status(e.message,true);}}finally{if(token===epoch)busy=false;}}
$('open').onclick=()=>$('file').click();$('file').onchange=e=>{if(e.target.files[0]&&canReplace())load(e.target.files[0]);e.target.value='';};
$('examples').onchange=async e=>{if(!e.target.value||!canReplace())return;const token=++epoch;cancelGesture();busy=true;const name=e.target.value;try{const r=await fetch('./samples/'+encodeURIComponent(name));if(!r.ok)throw Error('Ejemplo no disponible');await load(new File([await r.blob()],name),token);}catch(err){if(token===epoch){busy=false;status(err.message,true);}}};
fetch('./samples/index.json').then(r=>r.json()).then(names=>{for(const name of names){const o=document.createElement('option');o.value=name;o.textContent=name;$('examples').append(o);}}).catch(()=>{});
for(const event of ['dragover','drop'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.toggle('drag',event==='dragover');if(event==='drop'&&e.dataTransfer.files[0]&&canReplace())load(e.dataTransfer.files[0]);});$('drop').ondragleave=()=>$('drop').classList.remove('drag');
for(const button of document.querySelectorAll('[data-tool]'))button.onclick=()=>{cancelGesture();tool=button.dataset.tool;$('paper').dataset.tool=tool;for(const b of document.querySelectorAll('button[data-tool]'))b.setAttribute('aria-pressed',String(b===button));status(tool==='erase'?'Arrastra para borrar trazos completos. Suelta para aplicar.':tool==='draw'?'Dibuja con ratón, dedo o lápiz. Grosor fijo.':'Desplázate por la página.');};
$('paper').dataset.tool='pan';
function point(e){const r=$('paper').getBoundingClientRect();return [Math.max(0,Math.min(view.size[0],(e.clientX-r.left)/r.width*view.size[0])),Math.max(0,Math.min(view.size[1],(e.clientY-r.top)/r.height*view.size[1]))];}
function preview(){const g=gesture;if(!g)return;g.el.setAttribute('points',g.points.map(p=>p.join(',')).join(' '));g.dot.setAttribute('cx',g.points[0][0]);g.dot.setAttribute('cy',g.points[0][1]);}
$('paper').onpointerdown=e=>{if(!view||busy||gesture||e.button!==0)return;if(tool==='pan'){if(e.pointerType!=='mouse')return;e.preventDefault();gesture={id:e.pointerId,tool:'pan',x:e.clientX,y:e.clientY,left:$('viewport').scrollLeft,top:$('viewport').scrollTop};$('paper').setPointerCapture(e.pointerId);return;}e.preventDefault();$('paper').focus({preventScroll:true});const points=[point(e)],width=tool==='erase'?20:Number($('width').value),color=$('color').value;const el=document.createElementNS(ns,'polyline');for(const [k,v] of Object.entries({fill:'none',stroke:tool==='erase'?'#e1604a':color,'stroke-width':width,'stroke-linecap':'round','stroke-linejoin':'round',opacity:tool==='erase'?0.3:1}))el.setAttribute(k,v);const dot=document.createElementNS(ns,'circle');dot.setAttribute('r',width/2);dot.setAttribute('fill',tool==='erase'?'#e1604a':color);dot.setAttribute('opacity',tool==='erase'?0.3:1);$('overlay').append(el,dot);gesture={id:e.pointerId,points,width,color,tool,el,dot};$('paper').setPointerCapture(e.pointerId);preview();};
function appendPoint(e){if(!gesture||gesture.id!==e.pointerId)return;const samples=e.getCoalescedEvents?.()||[];for(const sample of samples.length?samples:[e]){const p=point(sample),last=gesture.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>=0.3&&gesture.points.length<8192)gesture.points.push(p);}preview();}
$('paper').onpointermove=e=>{if(gesture&&gesture.id===e.pointerId){e.preventDefault();if(gesture.tool==='pan'){$('viewport').scrollLeft=gesture.left+gesture.x-e.clientX;$('viewport').scrollTop=gesture.top+gesture.y-e.clientY;}else appendPoint(e);}};
$('paper').onpointerup=e=>{if(!gesture||gesture.id!==e.pointerId)return;if(gesture.tool==='pan'){cancelGesture();return;}appendPoint(e);const g=gesture;gesture=null;$('paper').releasePointerCapture(e.pointerId);if(g.tool==='erase')action('erase',{points:g.points,radius:10});else {const rgba=[1,3,5].map(i=>parseInt(g.color.slice(i,i+2),16)/255);action('draw',{line:{points:g.points,width:g.width,rgba:[...rgba,1]}});}};
$('paper').onpointercancel=cancelGesture;$('paper').onlostpointercapture=()=>{if(gesture)cancelGesture();};
$('undo').onclick=()=>action('undo');$('redo').onclick=()=>action('redo');$('prev').onclick=()=>action('view',{page:page-1});$('next').onclick=()=>action('view',{page:page+1});$('zoom').onchange=()=>{cancelGesture();resize();};new ResizeObserver(resize).observe($('viewport'));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelGesture();return;}if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo');}});
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function filename(){return (view?.title||'Nota').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_');}
$('save').onclick=async()=>{if(!view||busy)return;cancelGesture();busy=true;const token=epoch;try{const data=await call('save');if(token!==epoch)return;download(data,filename()+'.nfedit','application/json');dirty=false;status('Proyecto descargado. Puedes volver a abrirlo aquí.');}catch(e){if(token===epoch)status(e.message,true);}finally{if(token===epoch)busy=false;}};
$('svg').onclick=()=>{if(view&&!busy)download(view.svg,`${filename()}-p${page+1}.svg`,'image/svg+xml');};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
